# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a6fe6cff219e720b387fb2350b204d4f0cb71904a7a093cd13d0f4fd2c396c9952f13cdec410fb704cdc63c930374b13613ba047acae9eaf3f3801af0009246

test:
  secret_key_base: 7f021f97c9015186699bbd4dc4dd4729009cc870c262e50920f9a4a646a4c8f899d0822059092dc2fa704f5d324aedbe8b1331834c0574f8c9c139904268426b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
